
try{
	console.log('1');
	throw 'helo';
	console.log('2');
} catch(err){

	console.log('end');
}